import = ["~/.config/alacritty/themes/eldritch.toml"]
live_config_reload = true

[env]
  TERM = "xterm-256color"

[window]
  decorations = "Buttonless"
  opacity = 0.95
  padding.y = 10

[font]
normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"


