[username]
style_user = '#a48cf2 bold'
style_root = 'white bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[.@.](white bold)[$hostname](#37f499 bold) '

[directory]
style = '#04d1f9 bold'
truncation_length = 0
truncate_to_repo = false
