name: CI

on:
  push:
    branches:
      - mainline
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --exclude-globs='nvim/lazy-lock.json'
